// <auto-generated />
using System;
using Invoicing.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Invoicing.Migrations
{
    [DbContext(typeof(InvoicingContext))]
    [Migration("20190104195512_DaysAndActivities")]
    partial class DaysAndActivities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Invoicing.Models.ActivityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activity");

                    b.Property<Guid>("DayID");

                    b.Property<int>("Hours");

                    b.HasKey("Id");

                    b.HasIndex("DayID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Invoicing.Models.CompanyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber");

                    b.Property<string>("Address");

                    b.Property<string>("BankName");

                    b.Property<string>("CompanyNumber");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SortCode");

                    b.Property<string>("Telephone");

                    b.Property<string>("VatNumber");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Invoicing.Models.ContractModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuyerAddress");

                    b.Property<string>("BuyerName")
                        .IsRequired();

                    b.Property<string>("BuyerReference");

                    b.Property<string>("PaymentDeadline");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Invoicing.Models.DayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Day")
                        .IsRequired();

                    b.Property<bool>("Weekday");

                    b.HasKey("Id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Invoicing.Models.EmployeeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Invoicing.Models.ActivityModel", b =>
                {
                    b.HasOne("Invoicing.Models.DayModel", "Day")
                        .WithMany()
                        .HasForeignKey("DayID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
